import type { Task } from "../../types/types";

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Thiết kế trang đăng nhập",
    description: "Xây dựng giao diện đăng nhập responsive theo mockup Figma",
    status: "done",
    priority: "high",
    assignee: "Minh Tuấn",
    dueDate: "2026-05-10",
    createdAt: "2026-05-01",
    tags: ["design", "frontend"],
  },

  {
    id: "2",
    title: "Cấu hình Redux Toolkit",
    description: "Khởi tạo store, slice và middleware cho toàn bộ ứng dụng",
    status: "done",
    priority: "high",
    assignee: "Việt Anh",
    dueDate: "2026-05-08",
    createdAt: "2026-05-01",
    tags: ["redux", "state-management"],
  },

  {
    id: "3",
    title: "Xây dựng trang Dashboard",
    description: "Hiển thị thống kê tổng quan: tổng task, trạng thái, tiến độ",
    status: "in_progress",
    priority: "high",
    assignee: "Việt Anh",
    dueDate: "2026-05-15",
    createdAt: "2026-05-02",
    tags: ["dashboard", "frontend"],
  },

  {
    id: "4",
    title: "Tích hợp API danh sách nhân viên",
    description: "Gọi API GET /employees và hiển thị dữ liệu lên bảng",
    status: "in_progress",
    priority: "medium",
    assignee: "Hồng Nhung",
    dueDate: "2026-05-18",
    createdAt: "2026-05-03",
    tags: ["api", "backend"],
  },

  {
    id: "5",
    title: "Viết unit test cho TaskSlice",
    description: "Kiểm thử các reducer: addTask, updateTask, deleteTask",
    status: "todo",
    priority: "medium",
    assignee: "Minh Tuấn",
    dueDate: "2026-05-22",
    createdAt: "2026-05-04",
    tags: ["testing", "redux"],
  },

  {
    id: "6",
    title: "Phân quyền người dùng (RBAC)",
    description: "Triển khai hệ thống phân quyền theo vai trò Admin / User / Manager",
    status: "todo",
    priority: "high",
    assignee: "Thanh Long",
    dueDate: "2026-05-25",
    createdAt: "2026-05-04",
    tags: ["auth", "security"],
  },

  {
    id: "7",
    title: "Tối ưu hiệu năng trang Task List",
    description: "Áp dụng pagination phía server, tránh load toàn bộ dữ liệu",
    status: "todo",
    priority: "medium",
    assignee: "Hồng Nhung",
    dueDate: "2026-05-28",
    createdAt: "2026-05-05",
    tags: ["performance", "frontend"],
  },

  {
    id: "8",
    title: "Thiết kế component CoreTable",
    description: "Bảng dùng chung hỗ trợ sort, filter, pagination và loading state",
    status: "done",
    priority: "high",
    assignee: "Việt Anh",
    dueDate: "2026-05-09",
    createdAt: "2026-05-02",
    tags: ["component", "design-system"],
  },

  {
    id: "9",
    title: "Cài đặt CI/CD pipeline",
    description: "Tích hợp GitHub Actions để tự động build và deploy lên staging",
    status: "in_progress",
    priority: "high",
    assignee: "Thanh Long",
    dueDate: "2026-05-20",
    createdAt: "2026-05-05",
    tags: ["devops", "ci-cd"],
  },

  {
    id: "10",
    title: "Xây dựng form thêm Task mới",
    description: "Form có validation với React Hook Form + Zod, hỗ trợ các trường bắt buộc",
    status: "in_progress",
    priority: "medium",
    assignee: "Minh Tuấn",
    dueDate: "2026-05-17",
    createdAt: "2026-05-06",
    tags: ["form", "frontend"],
  },

  {
    id: "11",
    title: "Viết tài liệu API nội bộ",
    description: "Mô tả endpoint, request/response schema bằng Swagger / OpenAPI",
    status: "todo",
    priority: "low",
    assignee: "Hồng Nhung",
    dueDate: "2026-05-30",
    createdAt: "2026-05-06",
    tags: ["documentation", "api"],
  },

  {
    id: "12",
    title: "Sửa lỗi filter không giữ state khi chuyển trang",
    description: "Lưu bộ lọc vào URL query params để persist khi navigate",
    status: "done",
    priority: "high",
    assignee: "Việt Anh",
    dueDate: "2026-05-07",
    createdAt: "2026-05-05",
    tags: ["bugfix", "frontend"],
  },

  {
    id: "13",
    title: "Responsive màn hình mobile cho trang Tasks",
    description: "Kiểm tra và chỉnh layout breakpoint từ sm đến xl",
    status: "todo",
    priority: "medium",
    assignee: "Minh Tuấn",
    dueDate: "2026-05-24",
    createdAt: "2026-05-07",
    tags: ["responsive", "css"],
  },

  {
    id: "14",
    title: "Tích hợp thông báo toast",
    description: "Hiển thị toast success / error sau mỗi hành động CRUD",
    status: "done",
    priority: "low",
    assignee: "Hồng Nhung",
    dueDate: "2026-05-10",
    createdAt: "2026-05-06",
    tags: ["ux", "frontend"],
  },

  {
    id: "15",
    title: "Chuẩn hóa cấu trúc thư mục dự án",
    description: "Tái cấu trúc folders theo feature-based architecture",
    status: "done",
    priority: "medium",
    assignee: "Thanh Long",
    dueDate: "2026-05-06",
    createdAt: "2026-05-01",
    tags: ["refactor", "architecture"],
  },

  {
    id: "16",
    title: "Thêm chức năng tìm kiếm task theo tiêu đề",
    description: "Debounce input search 300ms, highlight từ khóa trong kết quả",
    status: "in_progress",
    priority: "medium",
    assignee: "Việt Anh",
    dueDate: "2026-05-19",
    createdAt: "2026-05-08",
    tags: ["search", "frontend"],
  },

  {
    id: "17",
    title: "Xây dựng trang quản lý nhân sự",
    description: "CRUD thông tin nhân viên: họ tên, phòng ban, vị trí, trạng thái",
    status: "todo",
    priority: "high",
    assignee: "Hồng Nhung",
    dueDate: "2026-06-01",
    createdAt: "2026-05-08",
    tags: ["hr", "crud"],
  },

  {
    id: "18",
    title: "Dark mode cho toàn bộ ứng dụng",
    description: "Thêm toggle dark/light, lưu lựa chọn vào localStorage",
    status: "todo",
    priority: "low",
    assignee: "Minh Tuấn",
    dueDate: "2026-06-05",
    createdAt: "2026-05-09",
    tags: ["ui", "theme"],
  },

  {
    id: "19",
    title: "Kiểm thử E2E với Playwright",
    description: "Viết test case cho luồng: đăng nhập → tạo task → xóa task",
    status: "todo",
    priority: "medium",
    assignee: "Thanh Long",
    dueDate: "2026-06-03",
    createdAt: "2026-05-09",
    tags: ["testing", "e2e"],
  },

  {
    id: "20",
    title: "Review và merge Pull Request Dashboard",
    description: "Code review PR #42, chạy test, approve và merge vào nhánh main",
    status: "done",
    priority: "high",
    assignee: "Việt Anh",
    dueDate: "2026-05-11",
    createdAt: "2026-05-10",
    tags: ["review", "git"],
  },
];
